### ISSUE TITLE
run

### ISSUE THREAD

**Issue by imSunnyk** [Nicxzmiller/StudentSs#2]
what are the steps to execute this project?

**Comment by Nicxzmiller** [comment]
The application comes with a prebuilt environment of python 3 with the
required modules and libraries needed to run.

To run the application, follow the instructions bellow

1. Open terminal in the project folder
2. Run “source env/bin/activate”
3. Next, you run “python run.py”
4. Open the browser and run http://localhost:8080

For the machine learning classifiers

1. Open project folder – src – run “classifier.py”
2. Enter a cost function of your choice and press enter.
